version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    volumes:
      - '.:/go/src'
    depends_on:
      - 'db'
    tty:
      true
  db:
    image: 'mysql:8.0'
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - './tmp/mysql:/var/lib/mysql'
